/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.ui;


import hotel.tableModel.CustomCellRenderer;

import hotel.tableModel.BookingTableModel;

import java.awt.Color;

import java.util.Calendar;
import java.util.Date;


/**
 * Test class for date handling and table display
 * @author Faysal
 */
public class testing extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private Date first, last;
    private BookingTableModel bookingTableModel;
    
    public testing() {
        initComponents();
        initializeDates();
        setupTable();
    }

    private void initializeDates() {
        first = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(first);
        cal.add(Calendar.DAY_OF_MONTH, 9);
        last = cal.getTime();
        System.out.println("Date range: " + first + " to " + last);
    }

    private void setupTable() {
        tableModel.setBackground(Color.LIGHT_GRAY);
        bookingTableModel = new BookingTableModel(first.getTime()/1000, last.getTime()/1000);
        tableModel.setModel(bookingTableModel);
        tableModel.setDefaultRenderer(Object.class, new CustomCellRenderer());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(last);
        first = last;
        cal.add(Calendar.DAY_OF_MONTH, 9);
        last = cal.getTime();
        System.out.println("New date range: " + first + " to " + last);
        bookingTableModel = new BookingTableModel(first.getTime()/1000, last.getTime()/1000);
        tableModel.setModel(bookingTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Date Range Test");

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableModel);

        jButton1.setText("Next Range");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new testing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableModel;
    // End of variables declaration//GEN-END:variables
}
